//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FOTO> FOTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int CreateFoto(Nullable<int> uSUARIO_ID, string fOTO_URL, string cAPTION)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            var fOTO_URLParameter = fOTO_URL != null ?
                new ObjectParameter("FOTO_URL", fOTO_URL) :
                new ObjectParameter("FOTO_URL", typeof(string));
    
            var cAPTIONParameter = cAPTION != null ?
                new ObjectParameter("CAPTION", cAPTION) :
                new ObjectParameter("CAPTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateFoto", uSUARIO_IDParameter, fOTO_URLParameter, cAPTIONParameter);
        }
    
        public virtual int CreateUsuario(string nOME, string sOBRENOME, string fOTO_URL, string eMAIL, string tELEFONE, string aNIVERSARIO)
        {
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sOBRENOMEParameter = sOBRENOME != null ?
                new ObjectParameter("SOBRENOME", sOBRENOME) :
                new ObjectParameter("SOBRENOME", typeof(string));
    
            var fOTO_URLParameter = fOTO_URL != null ?
                new ObjectParameter("FOTO_URL", fOTO_URL) :
                new ObjectParameter("FOTO_URL", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var tELEFONEParameter = tELEFONE != null ?
                new ObjectParameter("TELEFONE", tELEFONE) :
                new ObjectParameter("TELEFONE", typeof(string));
    
            var aNIVERSARIOParameter = aNIVERSARIO != null ?
                new ObjectParameter("ANIVERSARIO", aNIVERSARIO) :
                new ObjectParameter("ANIVERSARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateUsuario", nOMEParameter, sOBRENOMEParameter, fOTO_URLParameter, eMAILParameter, tELEFONEParameter, aNIVERSARIOParameter);
        }
    
        public virtual int Curtir(Nullable<int> fOTO_ID, Nullable<int> uSUARIO_ID)
        {
            var fOTO_IDParameter = fOTO_ID.HasValue ?
                new ObjectParameter("FOTO_ID", fOTO_ID) :
                new ObjectParameter("FOTO_ID", typeof(int));
    
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Curtir", fOTO_IDParameter, uSUARIO_IDParameter);
        }
    
        public virtual int DeleteFoto(Nullable<int> fOTO_ID)
        {
            var fOTO_IDParameter = fOTO_ID.HasValue ?
                new ObjectParameter("FOTO_ID", fOTO_ID) :
                new ObjectParameter("FOTO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteFoto", fOTO_IDParameter);
        }
    
        public virtual int DeleteUsuario(Nullable<int> uSUARIO_ID)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUsuario", uSUARIO_IDParameter);
        }
    
        public virtual ObjectResult<GetFoto_Result> GetFoto(Nullable<int> fOTO_ID)
        {
            var fOTO_IDParameter = fOTO_ID.HasValue ?
                new ObjectParameter("FOTO_ID", fOTO_ID) :
                new ObjectParameter("FOTO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFoto_Result>("GetFoto", fOTO_IDParameter);
        }
    
        public virtual ObjectResult<GetFotos_Result> GetFotos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFotos_Result>("GetFotos");
        }
    
        public virtual ObjectResult<GetFotosAmigos_Result> GetFotosAmigos(Nullable<int> uSUARIO_ID)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFotosAmigos_Result>("GetFotosAmigos", uSUARIO_IDParameter);
        }
    
        public virtual ObjectResult<GetFotosCurtidas_Result> GetFotosCurtidas(Nullable<int> uSUARIO_ID)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFotosCurtidas_Result>("GetFotosCurtidas", uSUARIO_IDParameter);
        }
    
        public virtual ObjectResult<GetFotosUsuario_Result> GetFotosUsuario(Nullable<int> uSUARIO_ID)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFotosUsuario_Result>("GetFotosUsuario", uSUARIO_IDParameter);
        }
    
        public virtual ObjectResult<GetUsuario_Result> GetUsuario(Nullable<int> uSUARIO_ID)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsuario_Result>("GetUsuario", uSUARIO_IDParameter);
        }
    
        public virtual ObjectResult<GetUsuarios_Result> GetUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsuarios_Result>("GetUsuarios");
        }
    
        public virtual ObjectResult<Nullable<int>> QtdCurtidas(Nullable<int> fOTO_ID)
        {
            var fOTO_IDParameter = fOTO_ID.HasValue ?
                new ObjectParameter("FOTO_ID", fOTO_ID) :
                new ObjectParameter("FOTO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("QtdCurtidas", fOTO_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> QtsUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("QtsUsuarios");
        }
    
        public virtual ObjectResult<Seguidores_Result> Seguidores(Nullable<int> uSUARIO_ID)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));

            //return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Seguidores_Result>("Seguidores", uSUARIO_IDParameter);
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Seguidores_Result>("Seguidores", uSUARIO_IDParameter);
        }
    
        public virtual ObjectResult<Seguindo_Result> Seguindo(Nullable<int> uSUARIO_ID)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Seguindo_Result>("Seguindo", uSUARIO_IDParameter);
        }
    
        public virtual int Seguir(Nullable<int> uSUARIO_ID_MASTER, Nullable<int> uSUARIO_ID_SLAVE)
        {
            var uSUARIO_ID_MASTERParameter = uSUARIO_ID_MASTER.HasValue ?
                new ObjectParameter("USUARIO_ID_MASTER", uSUARIO_ID_MASTER) :
                new ObjectParameter("USUARIO_ID_MASTER", typeof(int));
    
            var uSUARIO_ID_SLAVEParameter = uSUARIO_ID_SLAVE.HasValue ?
                new ObjectParameter("USUARIO_ID_SLAVE", uSUARIO_ID_SLAVE) :
                new ObjectParameter("USUARIO_ID_SLAVE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Seguir", uSUARIO_ID_MASTERParameter, uSUARIO_ID_SLAVEParameter);
        }
    
        public virtual int UpdateFoto(Nullable<int> fOTO_ID, Nullable<int> uSUARIO_ID, string fOTO_URL, string cAPTION)
        {
            var fOTO_IDParameter = fOTO_ID.HasValue ?
                new ObjectParameter("FOTO_ID", fOTO_ID) :
                new ObjectParameter("FOTO_ID", typeof(int));
    
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            var fOTO_URLParameter = fOTO_URL != null ?
                new ObjectParameter("FOTO_URL", fOTO_URL) :
                new ObjectParameter("FOTO_URL", typeof(string));
    
            var cAPTIONParameter = cAPTION != null ?
                new ObjectParameter("CAPTION", cAPTION) :
                new ObjectParameter("CAPTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateFoto", fOTO_IDParameter, uSUARIO_IDParameter, fOTO_URLParameter, cAPTIONParameter);
        }
    
        public virtual int UpdateUsuario(Nullable<int> uSUARIO_ID, string nOME, string sOBRENOME, string fOTO_URL, string eMAIL, string tELEFONE, string aNIVERSARIO)
        {
            var uSUARIO_IDParameter = uSUARIO_ID.HasValue ?
                new ObjectParameter("USUARIO_ID", uSUARIO_ID) :
                new ObjectParameter("USUARIO_ID", typeof(int));
    
            var nOMEParameter = nOME != null ?
                new ObjectParameter("NOME", nOME) :
                new ObjectParameter("NOME", typeof(string));
    
            var sOBRENOMEParameter = sOBRENOME != null ?
                new ObjectParameter("SOBRENOME", sOBRENOME) :
                new ObjectParameter("SOBRENOME", typeof(string));
    
            var fOTO_URLParameter = fOTO_URL != null ?
                new ObjectParameter("FOTO_URL", fOTO_URL) :
                new ObjectParameter("FOTO_URL", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var tELEFONEParameter = tELEFONE != null ?
                new ObjectParameter("TELEFONE", tELEFONE) :
                new ObjectParameter("TELEFONE", typeof(string));
    
            var aNIVERSARIOParameter = aNIVERSARIO != null ?
                new ObjectParameter("ANIVERSARIO", aNIVERSARIO) :
                new ObjectParameter("ANIVERSARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUsuario", uSUARIO_IDParameter, nOMEParameter, sOBRENOMEParameter, fOTO_URLParameter, eMAILParameter, tELEFONEParameter, aNIVERSARIOParameter);
        }
    }
}
