//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int comement_id { get; set; }
        public string uid { get; set; }
        public string post_id { get; set; }
        public string comment1 { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
