//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int post_id { get; set; }
        public int uid { get; set; }
        public string post_type { get; set; }
        public string post_caption { get; set; }
        public string post_photo { get; set; }
        public string post_video_url { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    }
}
