//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tagged_Post
    {
        public int fk_post_id { get; set; }
        public int fk_tag_Id { get; set; }
    }
}
