//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string uid { get; set; }
        public string nome { get; set; }
        public string nickname { get; set; }
        public Nullable<System.DateTime> brithday { get; set; }
        public string bio { get; set; }
        public string sexo { get; set; }
        public string site { get; set; }
        public string photo_url { get; set; }
    }
}
